### ISSUE TITLE
Clarify the relevant license terms (MIT?) for this project.

### ISSUE THREAD

**Issue by eelgnoy** [scottcorgan/tiny-emitter#15]

**Comment by scottcorgan** [comment]
Want to open  PR for it?

**Comment by eelgnoy** [comment]
Hi Scott,

I’m not sure if this email will get through, but I’m actually an attorney at Microsoft.  So I wouldn’t be able to scrape together enough coding skills to submit a pull request.  ☺

In a nutshell, one of the teams that I support is going to take a dependency on an open-source component that itself has a dependency on Tiny-Emitter.  So in order to comply with the relevant license terms, I’d need to know what Tiny-Emitter’s license terms are, which I couldn’t discern from the project site on Github.  So it would be great if the license was more discernable.  (I suspect that, going forward, this would be helpful for other adopters of Tiny-Emitter to want to be license-compliant.)

If you have any questions, please don’t hesitate to contact me.  My information is listed below.

Thank you!
Yong Lee

Yong Lee (CELA) | Senior Attorney | Microsoft Corporation | yonglee@microsoft.com<mailto:yonglee@microsoft.com> | Tel. 425.704.0349 | Mobile 425.516.8950 | One Microsoft Way, Redmond, WA 98052

**Comment by scottcorgan** [comment]
Done in https://github.com/scottcorgan/tiny-emitter/commit/04818f16eb0f1fdc783fbfb8824701aaab9a1295 and https://github.com/scottcorgan/tiny-emitter/commit/7e5898aba7471bc6d5467e95f8717655ca37b3da
