### ISSUE TITLE
Emit events on next tick

### ISSUE THREAD

**Issue by xixixao** [scottcorgan/tiny-emitter#2]
Is it a design choice to call the listeners immediately?

**Comment by ayamflow** [comment]
Shouldn't that be up to the user to emit on the next frame if needed ?
I'm thinking with other use cases in mind when one wants the listeners to trigger right after the event was emitted.

A simple example would be a backbone view with "life cycle events" like `beforeRender`/`render`/`afterRender` when you want each listener to fire before the next hook.

**Comment by Prinzhorn** [comment]
I'm with @ayamflow here. I trigger an event for every `requestAnimationFrame` with some custom data and every artificial delay would be undesirable.

**Comment by scottcorgan** [comment]
All good points. It's been the way it is for quite some time. Going to close in favor of keeping current functionality.

Open for more discussion thought.

**Comment by silverbucket** [comment]
@scottcorgan what about an optional init-time decision? 

```javascript
var emitter = new Emitter({
  emitOnNextTick: true   // default: false
});
```

**Comment by scottcorgan** [comment]
I do think it's an interesting feature, but I think wrapping tiny-emitter with that feature may be a better approach. Keeps it tiny. It's fairly easy to extend the class and overwrite the emit method in a new library.

```js
class TinyEmitterNextTick extends TinyEmitter {
  constructor () {
    super()
  }

  emit (...args) {
    process.nextTick(() => super.emit(...args))
  }
}

let emitter = new TinyEmitterNextTick()

// Use the tiny emitter api as normal
```
