### ISSUE TITLE
Is there any way to listen to all events irrespective to event name?

### ISSUE THREAD

**Issue by shubham1164** [scottcorgan/tiny-emitter#34]
Using
====
React-native 0.57

Issue
====
1. I want to listen to all the events without knowing the name of the event, is it possible?
2. I want to cancel all the events, without individually passing the name of all the events in the emitter.off() function

**Comment by rdewolff** [comment]
Was wondering the same.

**Comment by rdewolff** [comment]
Based on the source code https://github.com/scottcorgan/tiny-emitter/blob/master/dist/tinyemitter.js - there is no way to do it.

**Comment by scottcorgan** [comment]
I'd be happen to get that merged if you open a PR!

**Comment by Doogiemuc** [comment]
There actually is.   If you emit an event with `undefined` name, then all listeners will be notified.

_Is this a bug or a feature? :-)_
